require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccessoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Accessory. As you add validations to Accessory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "key" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccessoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all accessories as @accessories" do
      accessory = Accessory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:accessories).should eq([accessory])
    end
  end

  describe "GET show" do
    it "assigns the requested accessory as @accessory" do
      accessory = Accessory.create! valid_attributes
      get :show, {:id => accessory.to_param}, valid_session
      assigns(:accessory).should eq(accessory)
    end
  end

  describe "GET new" do
    it "assigns a new accessory as @accessory" do
      get :new, {}, valid_session
      assigns(:accessory).should be_a_new(Accessory)
    end
  end

  describe "GET edit" do
    it "assigns the requested accessory as @accessory" do
      accessory = Accessory.create! valid_attributes
      get :edit, {:id => accessory.to_param}, valid_session
      assigns(:accessory).should eq(accessory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Accessory" do
        expect {
          post :create, {:accessory => valid_attributes}, valid_session
        }.to change(Accessory, :count).by(1)
      end

      it "assigns a newly created accessory as @accessory" do
        post :create, {:accessory => valid_attributes}, valid_session
        assigns(:accessory).should be_a(Accessory)
        assigns(:accessory).should be_persisted
      end

      it "redirects to the created accessory" do
        post :create, {:accessory => valid_attributes}, valid_session
        response.should redirect_to(Accessory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accessory as @accessory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accessory.any_instance.stub(:save).and_return(false)
        post :create, {:accessory => { "key" => "invalid value" }}, valid_session
        assigns(:accessory).should be_a_new(Accessory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accessory.any_instance.stub(:save).and_return(false)
        post :create, {:accessory => { "key" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accessory" do
        accessory = Accessory.create! valid_attributes
        # Assuming there are no other accessories in the database, this
        # specifies that the Accessory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Accessory.any_instance.should_receive(:update_attributes).with({ "key" => "MyString" })
        put :update, {:id => accessory.to_param, :accessory => { "key" => "MyString" }}, valid_session
      end

      it "assigns the requested accessory as @accessory" do
        accessory = Accessory.create! valid_attributes
        put :update, {:id => accessory.to_param, :accessory => valid_attributes}, valid_session
        assigns(:accessory).should eq(accessory)
      end

      it "redirects to the accessory" do
        accessory = Accessory.create! valid_attributes
        put :update, {:id => accessory.to_param, :accessory => valid_attributes}, valid_session
        response.should redirect_to(accessory)
      end
    end

    describe "with invalid params" do
      it "assigns the accessory as @accessory" do
        accessory = Accessory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accessory.any_instance.stub(:save).and_return(false)
        put :update, {:id => accessory.to_param, :accessory => { "key" => "invalid value" }}, valid_session
        assigns(:accessory).should eq(accessory)
      end

      it "re-renders the 'edit' template" do
        accessory = Accessory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accessory.any_instance.stub(:save).and_return(false)
        put :update, {:id => accessory.to_param, :accessory => { "key" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accessory" do
      accessory = Accessory.create! valid_attributes
      expect {
        delete :destroy, {:id => accessory.to_param}, valid_session
      }.to change(Accessory, :count).by(-1)
    end

    it "redirects to the accessories list" do
      accessory = Accessory.create! valid_attributes
      delete :destroy, {:id => accessory.to_param}, valid_session
      response.should redirect_to(accessories_url)
    end
  end

end
